apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch7
  labels:
    component: elasticsearch7
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: elasticsearch7
  template:
    metadata:
      labels:
        component: elasticsearch7
    spec:
      containers:
        - name: elasticsearch7
          image: elasticsearch:7.17.9
          ports:
            - containerPort: 9200
              name: client
            - containerPort: 9300
              name: nodes
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx256m -Xms128m
            - name: discovery.type
              value: single-node
          resources:
            requests:
              memory: 500Mi
              cpu: 0.5
            limits:
              memory: 500Mi
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch7
  labels:
    component: elasticsearch7
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    component: elasticsearch7